# Generated by Django 5.2.1 on 2025-05-17 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('context', models.CharField(help_text='What are you saying goodbye to?', max_length=255)),
                ('message', models.TextField()),
                ('tone', models.CharField(choices=[('celebratory', 'Celebratory'), ('grateful', 'Grateful'), ('reflective', 'Reflective'), ('humorous', 'Humorous'), ('emotional', 'Emotional'), ('professional', 'Professional'), ('dramatic', 'Dramatic'), ('poetic', 'Poetic')], max_length=50)),
                ('template', models.CharField(max_length=50)),
                ('primary_color', models.CharField(default='#6D28D9', max_length=20)),
                ('background_color', models.CharField(default='#ffffff', max_length=20)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='page_media/')),
                ('file_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='pages.page')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
